layout_spectrum: 0.2885305
typography_spectrum: 0.05197133
color:
  saturation: 1
  lightness: 1
  brandStrength: 0.2990705
  rhythmicContrast: 1
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
name: jackieblaze
